DROP DATABASE IF EXISTS IOTDB;

CREATE DATABASE IOTDB;
USE IOTDB;

CREATE TABLE user (
	ID INT NOT NULL AUTO_INCREMENT,
	USERNAME VARCHAR(50) UNIQUE NOT NULL,
	PASSWORD VARCHAR(255) NOT NULL,
	FIRST_NAME VARCHAR(255) NOT NULL,
	LAST_NAME VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	LAST_LOGIN DATETIME,
	PRIMARY KEY (ID)
);

CREATE TABLE event (
	ID INT NOT NULL AUTO_INCREMENT,
	COMMAND VARCHAR(255) NOT NULL,
	USER_ID INT NOT NULL,
	INPUT_TIME DATETIME NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (USER_ID) REFERENCES user (ID)
);
