DROP DATABASE IF EXISTS leafplanner;

CREATE DATABASE leafplanner;
USE leafplanner;

CREATE TABLE user (
	ID          INT(11)                     AUTO_INCREMENT,
	FIRST_NAME  VARCHAR(255)    NOT NULL,
	LAST_NAME   VARCHAR(255)    NOT NULL,
	EMAIL       VARCHAR(255)    NOT NULL    UNIQUE,
    ROLE        VARCHAR(255)    NOT NULL,
	PASSWORD    VARCHAR(255)    NOT NULL,
    EXP_DATE    DATETIME        NOT NULL,
    LOCK_DATE   DATETIME,
    IS_ENABLED  BOOLEAN          NOT NULL    DEFAULT false,
	
    PRIMARY KEY (ID)
);

CREATE TABLE event (
	ID          INT(11)         NOT NULL    AUTO_INCREMENT,
	USER_ID     INT(11)         NOT NULL,
	TITLE       VARCHAR(255)    NOT NULL,
    DESCRIPTION VARCHAR(255),
    LOCATION    VARCHAR(255),
    START       DATETIME        NOT NULL,
    END         DATETIME,
    REPEAT_TIME      VARCHAR(30),

	PRIMARY KEY (ID),
	FOREIGN KEY (USER_ID) REFERENCES user (ID)
);

CREATE TABLE alert (
    ID          INT(11)         NOT NULL    AUTO_INCREMENT,
    EVENT_ID    INT(11)         NOT NULL,
    REMINDER    DATETIME        NOT NULL,

    PRIMARY KEY (ID),
    FOREIGN KEY (EVENT_ID) REFERENCES event (ID)
);