USE MILLION_TEST;

DROP TABLE IF EXISTS test_data;
CREATE TABLE test_data (
	ID INT NOT NULL AUTO_INCREMENT,
	Date VARCHAR(11),
	Name VARCHAR(100),
	PRIMARY KEY (ID)
);

DROP PROCEDURE IF EXISTS load_test_data;

DELIMITER #
CREATE PROCEDURE load_test_data()
BEGIN

DECLARE cnt INT UNSIGNED DEFAULT 0;
DECLARE mx INT UNSIGNED DEFAULT 3000000;
  START TRANSACTION;
  WHILE cnt < mx DO
    INSERT INTO test_data (Date, Name) VALUES ('25-SEP-2019','DICK FOONG');
    SET cnt=cnt+1;
  END WHILE;
  COMMIT;
END #

DELIMITER ;

CALL load_test_data();

SELECT * FROM test_data ORDER BY ID;

DROP PROCEDURE load_test_data;
